version: '3.8'

services:

  # =========================
  # BASE DE DATOS
  # =========================
  db:
    image: mysql:8.0
    container_name: hormisur_db
    restart: always

    env_file:
      - .env

    volumes:
      - db_data:/var/lib/mysql


  # =========================
  # BACKEND
  # =========================
  backend:
    build: ./backend/demo
    container_name: hormisur_backend
    restart: always

    env_file:
      - .env

    depends_on:
      - db


  # =========================
  # FRONTEND (ANGULAR)
  # =========================
  frontend:
    build: ./frontend
    container_name: hormisur_frontend
    restart: always

    depends_on:
      - backend


  # =========================
  # NGINX (LA CLAVE 🔥)
  # =========================
  nginx:
    image: nginx:latest
    container_name: hormisur_nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
      - backend


# =========================
# VOLUMEN DB
# =========================
volumes:
  db_data:
