events {}

http {
    server {
        listen 80;

        # =========================
        # FRONTEND (Angular)
        # =========================
        location / {
            proxy_pass http://frontend;
        }

        # =========================
        # BACKEND (Spring Boot)
        # =========================
        location /api/ {
            proxy_pass http://backend:8080/;
        }
    }
}
